/* eslint-disable */
/* global WebImporter */
/**
 * Parser for cards-steps. Base: cards. Purpose: process-steps.
 * Source: USAA checking page — "Opening an account is fast and easy." step sequence.
 * Generated by excat import-parser sub-agent.
 *
 * Block library convention: matches "Cards (no images)" — 1 column, one row per
 * card. Each row's single cell holds the card text content: heading + description
 * (+ optional CTA). No images in these process-step cards, so the 1-column form
 * is used. Steps are numbered automatically by the block's decorate() in document
 * order, so no number badge is emitted here.
 *
 * Source structure: <section class="usaa-aem-process-step"> ... <ol class="usaa-step-list">
 *   <li class="step"> .usaa-step-headline (heading text) + .usaa-step-body-text (body copy) </li> ...
 */
export default function parse(element, { document }) {
  // The DOM contains two copies of the step list (a public block and an
  // "authenticated-only" duplicate). Scope to the first step list so steps
  // are not emitted twice.
  const stepList = element.querySelector('ol.usaa-step-list') || element;
  const steps = Array.from(stepList.querySelectorAll(':scope > li.step, li.step'));

  const cells = [];

  steps.forEach((step) => {
    // Heading: promote the step headline to a semantic <h3>.
    const headlineEl = step.querySelector('.usaa-step-headline, [class*="step-headline"]');
    // Body: rich content (paragraphs, inline links) for the step.
    const bodyEl = step.querySelector('.usaa-step-body-text, [class*="step-body"]');

    const cellContent = [];

    if (headlineEl) {
      const heading = document.createElement('h3');
      heading.innerHTML = headlineEl.innerHTML.trim();
      cellContent.push(heading);
    }

    if (bodyEl) {
      // Preserve the body's inner nodes (paragraphs, links) as-is.
      Array.from(bodyEl.childNodes).forEach((node) => cellContent.push(node));
    }

    // Only emit a row if the step has content. 1-column: one cell per card.
    if (cellContent.length) cells.push([cellContent]);
  });

  // Empty-block guard: nothing extracted, unwrap in place.
  if (!cells.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'cards-steps', cells });
  element.replaceWith(block);
}
