/* eslint-disable */
/* global WebImporter */
/**
 * Parser for faq-expand. Base: faq. Purpose: faq-accordion.
 * Source: USAA checking page — "USAA Classic Checking FAQ" accordion.
 * Generated by excat import-parser sub-agent.
 *
 * Block model (Document Authoring): each authored row is one Q&A item —
 * first cell = question, second cell = answer (rich content, may contain
 * lists/paragraphs). The block's decorate() builds the accordion and the
 * "Expand all" toggle, so no toggle button is emitted here.
 *
 * Source structure: <section class="usaa-aem-faq-block"> ... .rds-accordion
 *   .rds-accordion__section
 *     button.rds-accordion__trigger > span (question text, with a leading
 *       screen-reader-only span to strip)
 *     .rds-accordion__panel (answer rich content)
 */
export default function parse(element, { document }) {
  const sections = Array.from(element.querySelectorAll('.rds-accordion__section, [class*="accordion-section"]'));

  const cells = [];

  sections.forEach((section) => {
    // Question: text inside the trigger button, excluding the screen-reader span.
    const trigger = section.querySelector('.rds-accordion__trigger, [class*="trigger"]');
    let question = '';
    if (trigger) {
      const clone = trigger.cloneNode(true);
      // Remove decorative icon and screen-reader-only content.
      clone.querySelectorAll('img, .rds-globals__screen-reader').forEach((n) => n.remove());
      question = (clone.textContent || '').trim();
    }

    // Answer: rich content within the panel.
    const panel = section.querySelector('.rds-accordion__panel, [class*="panel"]');
    const answerContent = [];
    if (panel) {
      // Unwrap the panel's meaningful content (paragraphs, lists) and preserve it.
      Array.from(panel.childNodes).forEach((node) => answerContent.push(node.cloneNode(true)));
    }

    if (!question) return;

    const questionCell = document.createElement('div');
    questionCell.textContent = question;

    const answerCell = document.createElement('div');
    answerContent.forEach((node) => answerCell.append(node));

    cells.push([questionCell, answerCell]);
  });

  // Empty-block guard. Some pages (e.g. the credit-cards storefront) render the
  // accordion's Q&A dynamically, so the scraped HTML has only the heading. In
  // that case, preserve the section's heading as default content rather than a
  // block, and drop the empty accordion shell + "Expand all" button.
  if (!cells.length) {
    const heading = element.querySelector('h2, h3');
    element.replaceWith(...(heading ? [heading] : []));
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'faq-expand', cells });
  element.replaceWith(block);
}
