/* eslint-disable */
/* global WebImporter */
/**
 * Parser for hero-callout. Base: hero. Purpose: cta-banner.
 * Source: USAA checking page — closing "Keep more of your money" CTA banner.
 * Generated by excat import-parser sub-agent.
 *
 * NOTE ON STRUCTURE: hero-callout is a genuinely custom local block. Its
 * decorate() (blocks/hero-callout/hero-callout.js) expects ONE row whose
 * columns are a text content cell (heading + primary button + secondary link)
 * and an optional media cell (side illustration). This differs from the
 * generic collection "Hero" (3-row, 1-column) convention; the local block's
 * contract governs how the imported content renders, so a single 2-cell row
 * (or 1-cell when text-only) is emitted here.
 *
 * Source structure: <section class="callout-block-authored-content"> ...
 *   .aem-callout-block__illustration-group
 *     .aem-callout-block__illustration-group-illustration (spotlight image)
 *     .aem-callout-block__illustration-group-content (heading + CTA links)
 *
 * Media stays local: the illustration uses a local ./images/*.png; inline
 * base64 data-URI decorations are ignored.
 */
export default function parse(element, { document }) {
  // Scope to the first authored callout (a duplicate authenticated-only copy exists).
  const content = element.querySelector('.aem-callout-block__illustration-group-content, [class*="illustration-group-content"]')
    || element;

  // Heading.
  const headingSrc = content.querySelector('h1, h2, h3, [class*="headline-1"], [class*="headline-2"]');

  // CTA links: primary button + secondary/tertiary link.
  const ctaLinks = Array.from(content.querySelectorAll('a[class*="button"], a.rds-button__primary, a.rds-button__tertiary'))
    // De-duplicate in case of overlapping class matches.
    .filter((a, i, arr) => arr.indexOf(a) === i);

  // Optional description paragraph(s).
  const descSrc = content.querySelector('p, [class*="paragraph-large"]');

  // Build the text cell.
  const textCell = [];
  if (headingSrc) {
    const h = document.createElement('h2');
    h.innerHTML = headingSrc.innerHTML.trim();
    textCell.push(h);
  }
  if (descSrc && descSrc.textContent.trim()) {
    const p = document.createElement('p');
    p.innerHTML = descSrc.innerHTML.trim();
    textCell.push(p);
  }
  ctaLinks.forEach((a) => {
    // Strip screen-reader-only spans and <br> inside the link, keep the label.
    const link = a.cloneNode(true);
    link.querySelectorAll('.rds-globals__screen-reader, br').forEach((n) => n.remove());
    link.textContent = (link.textContent || '').trim();
    const wrap = document.createElement('p');
    wrap.append(link);
    textCell.push(wrap);
  });

  // Optional image cell: prefer a local (non-data-URI) illustration image.
  const illustration = element.querySelector('.aem-callout-block__illustration-group-illustration, [class*="illustration-group-illustration"]');
  let imageEl = null;
  if (illustration) {
    imageEl = Array.from(illustration.querySelectorAll('img'))
      .find((img) => img.getAttribute('src') && !img.getAttribute('src').startsWith('data:'));
  }

  // Empty-block guard.
  if (!textCell.length && !imageEl) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const row = imageEl ? [textCell, [imageEl]] : [textCell];
  const cells = [row];

  const block = WebImporter.Blocks.createBlock(document, { name: 'hero-callout', cells });
  element.replaceWith(block);
}
