/* eslint-disable */
/* global WebImporter */
/**
 * Parser for table-rate. Base: table. Purpose: rate-data.
 * Source: USAA checking page — "Current USAA Classic Checking rate" APY table.
 * Generated by excat import-parser sub-agent.
 *
 * Block library convention: "Table" — multiple columns and rows; each authored
 * row is a row of data with cells across the columns. The block's decorate()
 * treats the first authored row as the header (th) and the rest as data (td),
 * so the header row is emitted first here, preserving the source table's
 * column structure ("Daily ledger balance", "Annual Percentage Yield (APY)").
 *
 * Source structure: <section class="usaa-aem-data-table"> contains a
 * responsive (non-stacked) <table class="rds-table"> with <thead>/<tbody>, plus
 * a stacked duplicate (table--stacked). Extract only the non-stacked table.
 */
export default function parse(element, { document }) {
  // Prefer the non-stacked responsive table; fall back to the first table.
  const tables = Array.from(element.querySelectorAll('table'));
  const table = tables.find((t) => !t.classList.contains('rds-table--stacked')) || tables[0];

  if (!table) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const cells = [];

  // Header row: from <thead> if present, else the first row.
  const headerCells = Array.from(table.querySelectorAll('thead th, thead td'));
  if (headerCells.length) {
    cells.push(headerCells.map((c) => {
      const div = document.createElement('div');
      div.textContent = (c.textContent || '').trim();
      return div;
    }));
  }

  // Data rows: each <tbody> <tr> becomes one cells[] row.
  const bodyRows = Array.from(table.querySelectorAll('tbody > tr'));
  bodyRows.forEach((tr) => {
    const rowCells = Array.from(tr.children).map((cell) => {
      // Preserve rich cell content (paragraphs, dynamic-data spans, etc.).
      const div = document.createElement('div');
      Array.from(cell.childNodes).forEach((node) => div.append(node.cloneNode(true)));
      if (!div.textContent.trim() && !div.querySelector('img')) {
        div.textContent = (cell.textContent || '').trim();
      }
      return div;
    });
    if (rowCells.length) cells.push(rowCells);
  });

  // Empty-block guard.
  if (!cells.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  // Pad short rows so every row has the same column count.
  const colCount = Math.max(...cells.map((r) => r.length));
  cells.forEach((row) => {
    while (row.length < colCount) row.push('');
  });

  const block = WebImporter.Blocks.createBlock(document, { name: 'table-rate', cells });
  element.replaceWith(block);
}
